Add test to selectively choose between string_ref or string_view
`boost::string_ref` is deprecated and doesn't play nice with
`boost::string_view`:

```
error: no matching function for call to ‘trial::protocol::json::basic_reader<char>::basic_reader(boost::string_view)’
     json::reader reader(boost::string_view(raw_json_data, raw_json_data_size));
note:   no known conversion for argument 1 from ‘boost::string_view {aka boost::basic_string_view<char, std::char_traits<char> >}’ to ‘const view_type& {aka const boost::basic_string_ref<char, std::char_traits<char> >&}’
```

However, we don't replace one with the other so we can support older
Boost releases.